name: Manual Deploy Angular App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (ex: production)"
        required: false
        default: "production"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Create file squarecloud.config
        run: |
          cat <<EOF > dist/squarecloud.config
          MAIN=expense-tracker-frontend/browser/index.html
          MEMORY=512
          VERSION=recommended
          DISPLAY_NAME=Expense-Tracker-Frontend
          AUTORESTART=true
          SUBDOMAIN=expense-tracker
          EOF

      - name: Compact project
        run: |
          cd dist/
          zip -r app.zip ./*
          mv app.zip ../

      - name: Deploy to Square Cloud
        run: |
          curl -X POST https://api.squarecloud.app/v2/apps \
            -H "Authorization: ${{ secrets.SQUARE_TOKEN }}" \
            -F "file=@app.zip"

      # - name: Install Vercel CLI
      #   run: npm install -g vercel

      # - name: Deploy to Vercel
      #   run: |
      #     vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --cwd ./dist/expense-tracker-frontend/browser
