name: Manual Deploy Angular App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (ex: production)"
        required: false
        default: "production"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Install Square Cloud CLI
        run: |
          curl -fsSL https://cli.squarecloud.app/install | bash

      - name: Authenticate with Square Cloud CLI
        run: square auth ${{ secrets.SQUARE_TOKEN }}

      - name: Deploy with Square Cloud CLI
        run: |
          cd dist/
          square deploy

      # - name: Install Vercel CLI
      #   run: npm install -g vercel

      # - name: Deploy to Vercel
      #   run: |
      #     vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --cwd ./dist/expense-tracker-frontend/browser
