name: Auto Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        env: 
          API_URL: ${{ secrets.PROD_API_URL }}
        run: npm run build

      - name: Create file squarecloud.config
        run: |
          cat <<EOF > dist/expense-tracker-frontend/browser/squarecloud.config
          MAIN=index.html
          MEMORY=512
          VERSION=recommended
          DISPLAY_NAME=Expense-Tracker-Frontend
          AUTORESTART=true
          SUBDOMAIN=expense-tracker
          EOF

      - name: Compact project
        run: |
          cd dist/expense-tracker-frontend/browser
          zip -r app.zip ./*
          mv app.zip ../../..

      - name: Deploy to Square Cloud
        run: |
          curl -X POST https://api.squarecloud.app/v2/apps/3c4b2bf33fda4208ac00207e194a658a/commit \
            -H "Authorization: ${{ secrets.SQUARE_TOKEN }}" \
            -F "file=@app.zip"
